[repository]
# The name of the github organization / person owner, e.g. tauffer-consulting.
# Must be in lower-case letters
REGISTRY_NAME = "jc-chen157"

# The name of this Pieces repository
REPOSITORY_NAME = "jiajun-template"
REPOSITORY_LABEL = "jiajun-template"

# The version of this Pieces release
# Attention: changing this will create a new release
VERSION = "0.0.1.3"
